import path from "path";
import fs from "fs";

import React from "react";
import express from "express";
import ReactDOMServer from "react-dom/server";
import { StaticRouter } from "react-router-dom";

import App from "../src/App";

const PORT = process.env.PORT || 10080;
const app = express();

/*
using index:false to prevent ./build/index.html to be server by default by express
*/
app.use(
  express.static("./build", {
    index: false,
  })
);

/*
default root
 */
app.get("/*", (req, res) => {
  const app = ReactDOMServer.renderToString(
    <StaticRouter location={req.url} context={{}}>
      <App />
    </StaticRouter>
  );

  const indexFile = path.resolve("./build/index.html");
  /* 
    Reading html generated by react scripts and replace with rendered app to keep the cache bust and precaching in CRA intact
  */
  fs.readFile(indexFile, "utf8", (err, data) => {
    if (err) {
      console.error("Something went wrong:", err);
      return res.status(500).send("Oops, better luck next time!");
    }

    return res.send(
      data.replace('<div id="root"></div>', `<div id="root">${app}</div>`)
    );
  });
});

app.listen(PORT, () => {
  console.log(`😎 Server is listening on port ${PORT}`);
});
